version: "3"
services:

  modsar:
    build:
      context: processing
      dockerfile: Dockerfile
      args:
        - JAR_PATH:/opt
        - CDK_VERSION:2.2
    volumes:
      - ./processing/modSAR:/mnt/code/modSAR
      - ./processing/notebooks:/mnt/code
      - ./data:/mnt/data
      - ./CPLEX_Studio1263/cplex/bin/x86-64_linux:/opt/cplex
    environment:
      - JAR_PATH=/opt
      - CDK_VERSION=2.2
    ports:
      - 8888:8888
